### FOR IDEA INTELLIJ HTTP CLIENT

### SEND anthropic prompt
POST http://localhost:8070/api/anthropic
Content-Type: application/json

{
  "prompt": "Przygotuj Hello World w spring boot"
}


### SEND anthropic prompt
POST http://localhost:8070/api/conversation/4/anthropic
Content-Type: application/json

{
  "prompt": "Dodaj konfiguracje dla K8S"
}



### GET all conversation
GET http://localhost:8070/api/conversations

### GET conversation by ID
GET http://localhost:8070/api/conversation/3

### GET ALL SYSTEM prompts
GET http://localhost:8070/api/systemPrompts